name: Ansible
on: workflow_dispatch
jobs:
  recall:
    uses: ./.github/workflows/new.yml
  ok:
    runs-on: ubuntu-latest
    container: 
      image: quay.io/ansible/ansible-runner:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run action
        uses: ./.github/actions/myactions

     
