name: test
on: workflow_dispatch
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: run fetch details
        uses: actions/checkout@v3
      - name: run cmd
        run: ansible-playbook -i inventory.ini ansible1.yml
